/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as vscode from 'vscode';
import { ILogService } from '../../../platform/log/common/logService';
import { CancellationToken } from '../../../util/vs/base/common/cancellation';
import {
	AuthRequiredError,
	DataKeyInvalidError,
	IPatentBackendClient,
} from './patentBackendClient';
import { PatentDataKeysStore } from './patentDataKeysStore';
import { FlowLeapAuthenticationProvider } from './flowleapAuthProvider';
import { NON_BYOK_VENDORS } from './patentEndpointProvider';
import { computeAccountState } from '../common/accountSection';

/**
 * The FlowLeap Settings sidebar (see CONTEXT.md): a webview VIEW in its own activity-bar
 * container (gear icon) with input fields for the BYO patent-data keys — the EPO OPS
 * Consumer Key + Consumer Secret pair and the USPTO ODP API Key — plus an "Add AI Model"
 * button into the BYOK Manage Models flow. It replaced the FlowLeap Settings editor tab
 * (which itself replaced the #32 quick-pick chain) behind the same `flowleap.patentDataKeys`
 * command, so every existing deep link (Setup view rows, the mid-chat invalid-key toast, the
 * shell's Settings entry points) lands here.
 *
 * Security invariants (ADR 0005): values go straight to {@link PatentDataKeysStore}
 * (SecretStorage) and are never logged; the webview only ever RECEIVES presence booleans —
 * stored key material never round-trips into the view.
 *
 * "Test connection" rides the normal request seam on purpose: the backend's key-forwarding
 * middleware (#30) eagerly validates the EPO pair on ANY guarded request and answers
 * `400 patent_provider_key_invalid` with a `provider` field, so a cheap request doubles as
 * a per-provider probe — no dedicated test endpoint needed. Saving auto-runs the test so a
 * typo is caught at entry, not mid-research (the key is kept either way — a sign-in or
 * connectivity problem must not block key entry).
 */

export const PATENT_DATA_KEYS_COMMAND = 'flowleap.patentDataKeys';

export const SETTINGS_VIEW_ID = 'flowleap.settingsView';

/** Auto-generated by the workbench for the contributed view; reveals the settings sidebar. */
const SETTINGS_VIEW_FOCUS_COMMAND = `${SETTINGS_VIEW_ID}.focus`;

/** The Agents window materializes no activity-bar views, so the auto-generated
 *  focus command never registers there — probe before executing. */
async function canFocusSettingsView(): Promise<boolean> {
	const commands = await vscode.commands.getCommands(true);
	return commands.includes(SETTINGS_VIEW_FOCUS_COMMAND);
}

const SHOW_SETUP_ON_STARTUP_SETTING = 'flowleap.showSetupOnStartup';

const EPO_SIGNUP_URL = 'https://developers.epo.org/';
const USPTO_SIGNUP_URL = 'https://data.uspto.gov/myodp';

/** A guarded GET that performs no USPTO call — with EPO headers attached, the backend's
 *  eager mint validates the pair, so the response IS the EPO verdict. */
const EPO_PROBE_PATH = '/citation-search/health';
/** A USPTO-backed call so the forwarded ODP key is actually exercised. */
const USPTO_PROBE_PATH = '/citation-search';
const USPTO_PROBE_BODY = { applicationNumber: '16123456' };

type Provider = 'epo' | 'uspto';

export interface TestConnectionResult {
	readonly ok: boolean;
	readonly message: string;
	/** On a key rejection: the provider the backend actually blamed (it may differ from the
	 *  one under test — the view routes the error to that provider's section). */
	readonly failedProvider?: Provider;
}

/**
 * Probe the backend to verify the CONFIGURED key for `provider`. Pure logic (no UI) so
 * it is unit-testable; the view wraps it in inline per-provider status lines.
 */
export async function testPatentDataConnection(client: IPatentBackendClient, provider: Provider): Promise<TestConnectionResult> {
	try {
		if (provider === 'epo') {
			await client.get(EPO_PROBE_PATH, CancellationToken.None, { timeoutMs: 15_000 });
			return { ok: true, message: 'EPO OPS credentials verified.' };
		}
		await client.post(USPTO_PROBE_PATH, USPTO_PROBE_BODY, CancellationToken.None, { timeoutMs: 15_000 });
		return { ok: true, message: 'USPTO ODP key verified.' };
	} catch (error) {
		if (error instanceof DataKeyInvalidError) {
			// The backend names the failing provider — it may differ from the one under test
			// (e.g. testing USPTO while a broken EPO pair is configured fails the eager EPO
			// validation first). Report what actually failed.
			const failed = error.provider === 'epo' ? 'EPO OPS credentials' : 'USPTO ODP key';
			return {
				ok: false,
				message: `${failed} rejected by the provider. ${error.provider === provider ? 'Update the key and test again.' : 'Fix or clear that provider first, then re-test.'}`,
				failedProvider: error.provider === 'epo' ? 'epo' : 'uspto',
			};
		}
		if (error instanceof AuthRequiredError) {
			return { ok: false, message: 'Sign in to FlowLeap first (the test runs through your FlowLeap account).' };
		}
		return { ok: false, message: `Could not reach the FlowLeap backend: ${error instanceof Error ? error.message : String(error)}` };
	}
}

interface ProviderSpec {
	readonly provider: Provider;
	readonly label: string;
	readonly signupUrl: string;
}

const PROVIDERS: readonly ProviderSpec[] = [
	{ provider: 'epo', label: 'EPO OPS (European Patent Office)', signupUrl: EPO_SIGNUP_URL },
	{ provider: 'uspto', label: 'USPTO ODP (US Patent Office)', signupUrl: USPTO_SIGNUP_URL },
];

/** Presence-only view state — the ONLY key-related data that ever reaches the webview. */
export interface DataKeysPageState {
	readonly epoConfigured: boolean;
	readonly usptoConfigured: boolean;
}

/** Messages the webview posts to the extension. */
type PageInMessage =
	| { readonly type: 'ready' }
	| { readonly type: 'saveEpo'; readonly key: string; readonly secret: string }
	| { readonly type: 'saveUspto'; readonly key: string }
	| { readonly type: 'test'; readonly provider: Provider }
	| { readonly type: 'clear'; readonly provider: Provider }
	| { readonly type: 'openSignup'; readonly provider: Provider }
	| { readonly type: 'openModelPicker' }
	| { readonly type: 'openPreferences' }
	| { readonly type: 'accountSignIn' }
	| { readonly type: 'accountSignOut' }
	| { readonly type: 'accountManageSubscription' };

/** Register the `flowleap.patentDataKeys` command: reveals the FlowLeap Settings sidebar. An
 *  optional provider argument (e.g. from the Setup view or the invalid-key toast) focuses
 *  that provider's section. */
export function registerPatentDataKeysCommand(viewProvider: PatentDataKeysViewProvider, logService: ILogService): vscode.Disposable {
	return vscode.commands.registerCommand(PATENT_DATA_KEYS_COMMAND, async (provider?: Provider) => {
		try {
			await viewProvider.reveal(provider === 'epo' || provider === 'uspto' ? provider : undefined);
		} catch (error) {
			logService.error(`[Patent AI] FlowLeap Settings view failed: ${error instanceof Error ? error.message : String(error)}`);
		}
	});
}

/**
 * On startup, reveal the FlowLeap Settings sidebar for users who have not set anything up
 * yet (no patent-data keys, no FlowLeap session, no BYOK model) so the first-run path is
 * "open app → sidebar is already on Settings → add keys". Opt-out via the
 * `flowleap.showSetupOnStartup` setting; configured users are never interrupted.
 */
export async function maybeShowSetupOnStartup(store: PatentDataKeysStore, authProvider: FlowLeapAuthenticationProvider, logService: ILogService): Promise<void> {
	if (!vscode.workspace.getConfiguration().get<boolean>(SHOW_SETUP_ON_STARTUP_SETTING, true)) {
		return;
	}
	await store.whenReady;
	const keys = store.getKeys();
	if (keys?.epo || keys?.usptoOdp) {
		return;
	}
	try {
		const sessions = await authProvider.getSessions();
		if (sessions.length > 0) {
			return;
		}
	} catch {
		// Unreadable session state — treat as signed out and keep evaluating.
	}
	try {
		const models = await vscode.lm.selectChatModels({});
		if (models.some(m => !NON_BYOK_VENDORS.has(m.vendor))) {
			return;
		}
	} catch {
		// Model enumeration unavailable this early — a fresh install has none anyway.
	}
	if (!(await canFocusSettingsView())) {
		return;
	}
	logService.info('[Patent AI] First-run setup incomplete — revealing the FlowLeap Settings sidebar');
	await vscode.commands.executeCommand(SETTINGS_VIEW_FOCUS_COMMAND);
}

/** The "FlowLeap Settings" webview view in its own activity-bar container. */
export class PatentDataKeysViewProvider implements vscode.WebviewViewProvider {

	private _view: vscode.WebviewView | undefined;
	private _pendingFocus: Provider | undefined;
	private readonly _disposables: vscode.Disposable[] = [];

	constructor(
		private readonly _store: PatentDataKeysStore,
		private readonly _client: IPatentBackendClient,
		private readonly _authProvider: FlowLeapAuthenticationProvider,
		private readonly _logService: ILogService,
	) { }

	register(): vscode.Disposable {
		this._disposables.push(
			vscode.window.registerWebviewViewProvider(SETTINGS_VIEW_ID, this, { webviewOptions: { retainContextWhenHidden: true } }),
			// Keep the badges live if keys change elsewhere (e.g. the store's initial async load).
			this._store.onDidChange(() => this._postState()),
			// Keep the Account section live across sign-in/out and the late profile-fetch `{changed}`.
			this._authProvider.onDidChangeSessions(() => void this._postAccountState()),
		);
		return vscode.Disposable.from(...this._disposables);
	}

	/** Reveal the settings sidebar, optionally scrolling to one provider's card. */
	async reveal(focus?: Provider): Promise<void> {
		if (!(await canFocusSettingsView())) {
			this._logService.info('[Patent AI] FlowLeap Settings view is not available in this window');
			return;
		}
		if (focus) {
			this._pendingFocus = focus;
		}
		await vscode.commands.executeCommand(SETTINGS_VIEW_FOCUS_COMMAND);
		if (this._view && focus) {
			this._pendingFocus = undefined;
			this._post({ type: 'focus', provider: focus });
		}
	}

	resolveWebviewView(webviewView: vscode.WebviewView): void {
		this._view = webviewView;
		// No localResourceRoots: everything is inlined, the view loads no resources at all.
		webviewView.webview.options = { enableScripts: true, localResourceRoots: [] };
		webviewView.webview.html = renderPatentDataKeysPageHtml(getNonce());
		webviewView.onDidDispose(() => {
			this._view = undefined;
		}, null, this._disposables);
		webviewView.webview.onDidReceiveMessage((message: PageInMessage) => this._onMessage(message), null, this._disposables);
	}

	private _post(message: object): void {
		void this._view?.webview.postMessage(message);
	}

	private _postState(focus?: Provider): void {
		const keys = this._store.getKeys();
		const state: DataKeysPageState = { epoConfigured: !!keys?.epo, usptoConfigured: !!keys?.usptoOdp };
		this._post({ type: 'state', ...state, focus });
	}

	private _postStatus(provider: Provider, kind: 'testing' | 'ok' | 'error' | 'warn' | 'info', message: string): void {
		this._post({ type: 'status', provider, kind, message });
	}

	/**
	 * Compute and post the Account section state (identity + subscription pill). Reads only data the
	 * auth provider already fetches; the pure {@link computeAccountState} owns the mapping so the view
	 * stays a reflector. Signed-out short-circuits without a subscription fetch.
	 */
	private async _postAccountState(): Promise<void> {
		const identity = this._authProvider.getIdentity();
		const snapshot = identity ? await this._authProvider.getSubscriptionSnapshot() : { status: 'unknown' as const };
		const state = computeAccountState(identity, snapshot, Date.now());
		this._post({ type: 'account', ...state });
	}

	/**
	 * Open the user's Polar customer portal in the browser. Fetches the URL through the backend-client
	 * seam (inheriting its typed 401/402 errors) and surfaces a friendly toast on failure so the button
	 * never appears broken.
	 */
	private async _openCustomerPortal(): Promise<void> {
		try {
			const portalUrl = await this._client.getCustomerPortalUrl(CancellationToken.None);
			await vscode.env.openExternal(vscode.Uri.parse(portalUrl));
		} catch (error) {
			this._logService.error(`[Patent AI] Manage subscription failed: ${error instanceof Error ? error.message : String(error)}`);
			void vscode.window.showErrorMessage('Could not open the FlowLeap subscription portal. Please try again in a moment.');
		}
	}

	private async _onMessage(message: PageInMessage): Promise<void> {
		try {
			switch (message.type) {
				case 'ready': {
					const focus = this._pendingFocus;
					this._pendingFocus = undefined;
					this._postState(focus);
					void this._postAccountState();
					return;
				}
				case 'saveEpo': {
					const key = message.key.trim();
					const secret = message.secret.trim();
					if (!key || !secret) {
						this._postStatus('epo', 'error', 'Enter both the consumer key and the consumer secret.');
						return;
					}
					await this._store.setEpoCredentials({ key, secret });
					await this._afterSave('epo');
					return;
				}
				case 'saveUspto': {
					const key = message.key.trim();
					if (!key) {
						this._postStatus('uspto', 'error', 'Enter the API key.');
						return;
					}
					await this._store.setUsptoOdpKey(key);
					await this._afterSave('uspto');
					return;
				}
				case 'test':
					await this._runTest(message.provider);
					return;
				case 'clear':
					// Confirmation is the view's two-step Clear button — no native dialog here.
					await this._store.clearProvider(message.provider);
					this._postStatus(message.provider, 'info', 'Removed from secure storage.');
					return;
				case 'openSignup': {
					const spec = PROVIDERS.find(s => s.provider === message.provider)!;
					await vscode.env.openExternal(vscode.Uri.parse(spec.signupUrl));
					return;
				}
				case 'openModelPicker':
					await vscode.commands.executeCommand('workbench.action.chat.manage');
					return;
				case 'openPreferences':
					await vscode.commands.executeCommand('workbench.action.openSettings', '@flowleap');
					return;
				case 'accountSignIn':
					// The canonical user-facing sign-in command owned by the FlowLeap auth provider.
					await vscode.commands.executeCommand('flowleap.signIn');
					return;
				case 'accountSignOut':
					await vscode.commands.executeCommand('patent-ai.signOut');
					return;
				case 'accountManageSubscription':
					await this._openCustomerPortal();
					return;
			}
		} catch (error) {
			this._logService.error(`[Patent AI] FlowLeap Settings view action failed: ${error instanceof Error ? error.message : String(error)}`);
		}
	}

	/** Save persisted — confirm, then auto-test so a typo is caught now, not mid-research. */
	private async _afterSave(provider: Provider): Promise<void> {
		this._postStatus(provider, 'info', 'Saved to secure storage.');
		await this._runTest(provider);
	}

	private async _runTest(provider: Provider): Promise<void> {
		this._postStatus(provider, 'testing', 'Testing connection…');
		const result = await testPatentDataConnection(this._client, provider);
		if (result.ok) {
			this._postStatus(provider, 'ok', result.message);
			return;
		}
		if (result.failedProvider && result.failedProvider !== provider) {
			// The OTHER provider's stored key blocked this test — flag its section too.
			this._postStatus(result.failedProvider, 'error', result.message);
			this._postStatus(provider, 'warn', 'Could not complete the test — fix the flagged key first.');
			return;
		}
		// A rejection is an error; signed-out / unreachable is a warning (the key was still saved).
		this._postStatus(provider, result.failedProvider ? 'error' : 'warn', result.message);
	}
}

/**
 * The view markup. Static skeleton only — all dynamic state (presence badges, status lines,
 * section focus) arrives via `state`/`status`/`focus` messages, and no key material is ever
 * embedded. Exported for tests.
 */
export function renderPatentDataKeysPageHtml(nonce: string): string {
	return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>FlowLeap Settings</title>
	<style>
		* { margin: 0; padding: 0; box-sizing: border-box; }
		body {
			font-family: var(--vscode-font-family, sans-serif);
			background: var(--vscode-sideBar-background, var(--vscode-editor-background));
			color: var(--vscode-foreground);
			font-size: 13px;
		}
		.container { max-width: 640px; margin: 0 auto; padding: 12px 14px 20px; }
		.privacy { color: var(--vscode-descriptionForeground); font-size: 12px; margin-bottom: 14px; }
		.card {
			background: var(--vscode-editorWidget-background, var(--vscode-editor-background));
			border: 1px solid var(--vscode-widget-border, var(--vscode-editorWidget-border, transparent));
			border-radius: 8px;
			padding: 14px;
			margin-bottom: 14px;
			transition: outline-color 0.4s;
			outline: 2px solid transparent;
		}
		.card.focused { outline-color: var(--vscode-focusBorder); }
		.account-identity { margin-bottom: 10px; }
		.account-name { font-size: 14px; font-weight: 600; }
		.account-email { color: var(--vscode-descriptionForeground); font-size: 12px; margin-top: 2px; word-break: break-all; }
		.pill {
			display: inline-block; font-size: 11px; padding: 2px 10px; border-radius: 10px; margin-bottom: 10px;
			background: color-mix(in srgb, var(--vscode-descriptionForeground) 18%, transparent);
			color: var(--vscode-descriptionForeground);
		}
		.pill.trial, .pill.active {
			background: color-mix(in srgb, var(--vscode-testing-iconPassed, #22c55e) 18%, transparent);
			color: var(--vscode-testing-iconPassed, #22c55e);
		}
		.pill.warn {
			background: color-mix(in srgb, var(--vscode-editorWarning-foreground, #f59e0b) 20%, transparent);
			color: var(--vscode-editorWarning-foreground, #f59e0b);
		}
		.account-signout { margin-left: auto; font-size: 12px; }
		[hidden] { display: none !important; }
		.card-header { display: flex; align-items: center; gap: 10px; margin-bottom: 4px; flex-wrap: wrap; }
		.card-title { font-size: 14px; font-weight: 600; flex: 1; }
		.badge {
			font-size: 11px; padding: 2px 9px; border-radius: 10px;
			background: color-mix(in srgb, var(--vscode-descriptionForeground) 18%, transparent);
			color: var(--vscode-descriptionForeground);
		}
		.badge.configured {
			background: color-mix(in srgb, var(--vscode-testing-iconPassed, #22c55e) 18%, transparent);
			color: var(--vscode-testing-iconPassed, #22c55e);
		}
		.card-desc { color: var(--vscode-descriptionForeground); margin-bottom: 12px; }
		.field { margin-bottom: 10px; }
		.field label { display: block; font-size: 12px; color: var(--vscode-foreground); margin-bottom: 3px; }
			.field-hint { display: block; font-size: 11px; color: var(--vscode-descriptionForeground); margin-bottom: 5px; line-height: 1.4; }
		.field input {
			width: 100%; padding: 6px 8px; border-radius: 3px;
			background: var(--vscode-input-background);
			color: var(--vscode-input-foreground);
			border: 1px solid var(--vscode-input-border, transparent);
			font-family: inherit; font-size: 13px;
		}
		.field input:focus { outline: 1px solid var(--vscode-focusBorder); }
		.buttons { display: flex; gap: 8px; margin-top: 12px; align-items: center; flex-wrap: wrap; }
		button {
			padding: 5px 14px; border-radius: 3px; border: none; cursor: pointer; font-size: 13px;
			background: var(--vscode-button-background); color: var(--vscode-button-foreground);
		}
		button:hover:not(:disabled) { background: var(--vscode-button-hoverBackground); }
		button.secondary {
			background: var(--vscode-button-secondaryBackground, transparent);
			color: var(--vscode-button-secondaryForeground, var(--vscode-foreground));
			border: 1px solid var(--vscode-widget-border, transparent);
		}
		button.secondary:hover:not(:disabled) { background: var(--vscode-button-secondaryHoverBackground); }
		button:disabled { opacity: 0.45; cursor: default; }
		button.danger {
			background: color-mix(in srgb, var(--vscode-errorForeground) 20%, transparent);
			color: var(--vscode-errorForeground);
			border: 1px solid var(--vscode-errorForeground);
		}
		.status { margin-top: 10px; font-size: 12px; min-height: 16px; }
		.status.ok { color: var(--vscode-testing-iconPassed, #22c55e); }
		.status.error { color: var(--vscode-errorForeground); }
		.status.warn { color: var(--vscode-editorWarning-foreground, #f59e0b); }
		.status.info, .status.testing { color: var(--vscode-descriptionForeground); }
		.get-key { margin-top: 10px; font-size: 12px; }
		a { color: var(--vscode-textLink-foreground); cursor: pointer; text-decoration: none; }
		a:hover { text-decoration: underline; }
		.footer { color: var(--vscode-descriptionForeground); font-size: 12px; margin-top: 18px; }
	</style>
</head>
<body>
	<div class="container">
		<div class="card" id="card-account">
			<div class="card-header">
				<div class="card-title">Account</div>
			</div>
			<div id="account-signed-out" hidden>
				<p class="card-desc">Sign in to FlowLeap to sync your subscription and patent access.</p>
				<div class="buttons">
					<button id="account-signin">Sign In</button>
				</div>
			</div>
			<div id="account-signed-in" hidden>
				<div class="account-identity">
					<div class="account-name" id="account-name" hidden></div>
					<div class="account-email" id="account-email" hidden></div>
				</div>
				<span class="pill" id="account-pill" hidden></span>
				<div class="buttons">
					<button class="secondary" id="account-manage" hidden>Manage Subscription</button>
					<a href="#" class="account-signout" id="account-signout">Sign out</a>
				</div>
			</div>
		</div>

		<div class="card" id="card-model">
			<div class="card-header">
				<div class="card-title">AI Model</div>
			</div>
			<p class="card-desc">Chat runs on your own AI provider key (Anthropic, OpenAI, OpenRouter, …).</p>
			<div class="buttons">
				<button id="add-model">Add AI Model</button>
			</div>
		</div>

		<p class="privacy">The patent-office keys below stay on this machine in secure storage and are only sent to reach the patent offices. They are never shown again once saved — entering a new value replaces the stored one.</p>

		<div class="card" id="card-epo">
			<div class="card-header">
				<div class="card-title">EPO OPS (European Patent Office)</div>
				<span class="badge" id="badge-epo">Not configured</span>
			</div>
			<p class="card-desc">European patent data. Needs the Consumer Key and Consumer Secret of an app on your EPO OPS account.</p>
			<div class="field">
				<label for="epo-key">Consumer Key</label>
					<span class="field-hint">Find it at developers.epo.org — My Apps → your app → Consumer Key.</span>
				<input type="password" id="epo-key" placeholder="Paste your Consumer Key">
			</div>
			<div class="field">
				<label for="epo-secret">Consumer Secret</label>
					<span class="field-hint">The matching Consumer Secret for that same app.</span>
				<input type="password" id="epo-secret" placeholder="Paste your Consumer Secret">
			</div>
			<div class="buttons">
				<button id="save-epo" disabled>Save</button>
				<button class="secondary" id="test-epo" disabled>Test Connection</button>
				<button class="secondary" id="clear-epo" disabled>Clear</button>
			</div>
			<div class="status" id="status-epo"></div>
			<div class="get-key">Don't have a key yet? <a href="#" id="signup-epo">Get one at developers.epo.org</a></div>
		</div>

		<div class="card" id="card-uspto">
			<div class="card-header">
				<div class="card-title">USPTO ODP (US Patent Office)</div>
				<span class="badge" id="badge-uspto">Not configured</span>
			</div>
			<p class="card-desc">US patent data and citation analysis. Needs an Open Data Portal API key.</p>
			<div class="field">
				<label for="uspto-key">API Key</label>
					<span class="field-hint">Find it at data.uspto.gov/myodp — My ODP → API key.</span>
				<input type="password" id="uspto-key" placeholder="Paste your API key">
			</div>
			<div class="buttons">
				<button id="save-uspto" disabled>Save</button>
				<button class="secondary" id="test-uspto" disabled>Test Connection</button>
				<button class="secondary" id="clear-uspto" disabled>Clear</button>
			</div>
			<div class="status" id="status-uspto"></div>
			<div class="get-key">Don't have a key yet? <a href="#" id="signup-uspto">Get one at data.uspto.gov/myodp</a></div>
		</div>

		<div class="footer">Looking for chat mode, projects folder and other preferences? <a href="#" id="open-preferences">All FlowLeap preferences…</a></div>
	</div>

	<script nonce="${nonce}">
		const vscode = acquireVsCodeApi();
		const $ = id => document.getElementById(id);
		const configured = { epo: false, uspto: false };

		function refreshButtons() {
			$('save-epo').disabled = !($('epo-key').value.trim() && $('epo-secret').value.trim());
			$('save-uspto').disabled = !$('uspto-key').value.trim();
			for (const p of ['epo', 'uspto']) {
				$('test-' + p).disabled = !configured[p];
				$('clear-' + p).disabled = !configured[p];
				const badge = $('badge-' + p);
				badge.textContent = configured[p] ? 'Configured' : 'Not configured';
				badge.classList.toggle('configured', configured[p]);
			}
		}

		function setStatus(provider, kind, message) {
			const el = $('status-' + provider);
			el.className = 'status ' + kind;
			el.textContent = (kind === 'ok' ? '✓ ' : kind === 'error' ? '✗ ' : kind === 'warn' ? '⚠ ' : '') + message;
		}

		function renderAccount(state) {
			const signedIn = state.signedIn === true;
			$('account-signed-out').hidden = signedIn;
			$('account-signed-in').hidden = !signedIn;
			if (!signedIn) {
				return;
			}
			const name = $('account-name');
			name.textContent = state.name || '';
			name.hidden = !state.name;
			const email = $('account-email');
			email.textContent = state.email || '';
			email.hidden = !state.email;
			const pill = $('account-pill');
			if (state.pill) {
				pill.textContent = state.pill.label;
				pill.className = 'pill ' + state.pill.tone;
				pill.hidden = false;
			} else {
				pill.hidden = true;
			}
			$('account-manage').hidden = !state.canManageSubscription;
		}

		function focusCard(provider) {
			const card = $('card-' + provider);
			card.scrollIntoView({ behavior: 'smooth', block: 'center' });
			card.classList.add('focused');
			setTimeout(() => card.classList.remove('focused'), 1600);
			$(provider === 'epo' ? 'epo-key' : 'uspto-key').focus();
		}

		// Two-step confirm for Clear: first click arms the button, second click (within 5s)
		// removes the key. No native dialog — everything stays in the view.
		const clearTimers = {};
		function disarmClear(p) {
			clearTimeout(clearTimers[p]);
			const btn = $('clear-' + p);
			btn.textContent = 'Clear';
			btn.classList.remove('danger');
			delete clearTimers[p];
		}

		window.addEventListener('message', e => {
			const m = e.data;
			if (m.type === 'state') {
				configured.epo = m.epoConfigured;
				configured.uspto = m.usptoConfigured;
				disarmClear('epo');
				disarmClear('uspto');
				refreshButtons();
				if (m.focus) { focusCard(m.focus); }
			} else if (m.type === 'status') {
				setStatus(m.provider, m.kind, m.message);
			} else if (m.type === 'focus') {
				focusCard(m.provider);
			} else if (m.type === 'account') {
				renderAccount(m);
			}
		});

		$('account-signin').addEventListener('click', () => vscode.postMessage({ type: 'accountSignIn' }));
		$('account-manage').addEventListener('click', () => vscode.postMessage({ type: 'accountManageSubscription' }));
		$('account-signout').addEventListener('click', e => { e.preventDefault(); vscode.postMessage({ type: 'accountSignOut' }); });
		$('add-model').addEventListener('click', () => vscode.postMessage({ type: 'openModelPicker' }));
		$('save-epo').addEventListener('click', () => {
			vscode.postMessage({ type: 'saveEpo', key: $('epo-key').value, secret: $('epo-secret').value });
			$('epo-key').value = ''; $('epo-secret').value = '';
			refreshButtons();
		});
		$('save-uspto').addEventListener('click', () => {
			vscode.postMessage({ type: 'saveUspto', key: $('uspto-key').value });
			$('uspto-key').value = '';
			refreshButtons();
		});
		for (const p of ['epo', 'uspto']) {
			$('test-' + p).addEventListener('click', () => vscode.postMessage({ type: 'test', provider: p }));
			$('signup-' + p).addEventListener('click', e => { e.preventDefault(); vscode.postMessage({ type: 'openSignup', provider: p }); });
			$('clear-' + p).addEventListener('click', () => {
				if (clearTimers[p] !== undefined) {
					disarmClear(p);
					vscode.postMessage({ type: 'clear', provider: p });
					return;
				}
				const btn = $('clear-' + p);
				btn.textContent = 'Confirm Remove?';
				btn.classList.add('danger');
				clearTimers[p] = setTimeout(() => disarmClear(p), 5000);
			});
		}
		$('open-preferences').addEventListener('click', e => { e.preventDefault(); vscode.postMessage({ type: 'openPreferences' }); });
		document.addEventListener('input', refreshButtons);

		refreshButtons();
		vscode.postMessage({ type: 'ready' });
	</script>
</body>
</html>`;
}

function getNonce(): string {
	let text = '';
	const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
	for (let i = 0; i < 32; i++) {
		text += possible.charAt(Math.floor(Math.random() * possible.length));
	}
	return text;
}
