/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { Codicon } from '../../../base/common/codicons.js';
import { ThemeIcon } from '../../../base/common/themables.js';

export interface PromptTemplate {
	name: string;
	prefix: string;
	description: string;
	body: string[];
}

export interface PromptCategory {
	id: string;
	label: string;
	description: string;
	icon: ThemeIcon;
	templates: PromptTemplate[];
}

export const patentPromptCategories: PromptCategory[] = [
	{
		id: 'prior-art-search',
		label: 'Prior Art Search',
		description: 'Search strategies, CQL queries, keyword expansion',
		icon: Codicon.search,
		templates: [
			{
				name: 'Prior Art Search Strategy',
				prefix: 'search-strategy',
				description: 'Develop a comprehensive prior art search strategy',
				body: [
					'<role>You are an expert patent searcher with deep knowledge of patent classification systems (IPC/CPC) and patent database search techniques.</role>',
					'',
					'<task>Develop a comprehensive prior art search strategy for the following patent/invention.</task>',
					'',
					'<context>',
					'Patent/Application Number: ${1:EP1234567}',
					'Title: ${2:Title of the invention}',
					'Key Technical Field: ${3:e.g., semiconductor manufacturing}',
					'</context>',
					'',
					'<instructions>',
					'1. Analyze the core technical features of the invention',
					'2. Identify relevant IPC/CPC classification codes',
					'3. Generate keyword sets (synonyms, related terms, broader/narrower terms)',
					'4. Propose CQL queries combining classifications and keywords',
					'5. Suggest non-patent literature sources to search',
					'6. Recommend a search execution order (most relevant first)',
					'</instructions>',
					'',
					'<output_format>',
					'## Search Strategy',
					'### Core Features',
					'### Classification Codes',
					'### Keyword Sets',
					'### CQL Queries',
					'### Non-Patent Literature Sources',
					'### Execution Plan',
					'</output_format>',
					'$0',
				],
			},
			{
				name: 'CQL Query Builder',
				prefix: 'cql-query',
				description: 'Build an Espacenet CQL query from technical features',
				body: [
					'<role>You are an expert in Espacenet CQL (Common Query Language) syntax for patent searching.</role>',
					'',
					'<task>Build optimized CQL queries for Espacenet based on the technical features below.</task>',
					'',
					'<context>',
					'Technical features to search:',
					'1. ${1:First key feature}',
					'2. ${2:Second key feature}',
					'3. ${3:Third key feature}',
					'Target classification: ${4:CPC or IPC code}',
					'</context>',
					'',
					'<instructions>',
					'- Generate 3-5 CQL queries from broad to narrow',
					'- Use field codes: ti= (title), ab= (abstract), cl= (claims), desc= (description), cpc= (CPC), ic= (IPC)',
					'- Use Boolean operators: AND, OR, NOT',
					'- Use proximity operators where appropriate',
					'- Include wildcard truncation (?) for word variations',
					'- Estimate result count for each query (rough order of magnitude)',
					'</instructions>',
					'',
					'<output_format>',
					'## CQL Queries (Broad → Narrow)',
					'### Query 1 (Broadest) — est. results: ~N',
					'```',
					'query here',
					'```',
					'### Query 2 — est. results: ~N',
					'```',
					'query here',
					'```',
					'</output_format>',
					'$0',
				],
			},
			{
				name: 'Keyword Expansion',
				prefix: 'keyword-expand',
				description:
					'Expand technical keywords with synonyms and related terms',
				body: [
					'<role>You are a patent linguist specializing in technical terminology across patent documents.</role>',
					'',
					'<task>Expand the following technical keywords into comprehensive search term sets.</task>',
					'',
					'<context>',
					'Technical domain: ${1:e.g., wireless communications}',
					'Keywords to expand:',
					'- ${2:keyword 1}',
					'- ${3:keyword 2}',
					'- ${4:keyword 3}',
					'</context>',
					'',
					'<instructions>',
					'For each keyword, provide:',
					'1. Direct synonyms',
					'2. Broader terms (genus)',
					'3. Narrower terms (species)',
					'4. Related technical terms',
					'5. Common patent phrasing variations',
					'6. Abbreviations and acronyms',
					'Group results as OR-combined sets for use in CQL queries.',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Citation Network Analysis',
				prefix: 'citation-analysis',
				description:
					'Analyze forward/backward citations for relevant prior art',
				body: [
					'<role>You are a patent analyst specializing in citation network analysis.</role>',
					'',
					'<task>Analyze the citation network of the following patent to identify the most relevant prior art documents.</task>',
					'',
					'<context>',
					'Patent Number: ${1:EP1234567}',
					'Backward citations (cited by this patent):',
					'${2:List of cited documents}',
					'',
					'Forward citations (patents citing this one):',
					'${3:List of citing documents}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify the most technically relevant backward citations',
					'2. Find common assignees or inventors in the citation network',
					'3. Identify citation clusters (groups of related patents)',
					'4. Suggest additional documents to review based on citation patterns',
					'5. Rank citations by relevance to the core invention',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Non-Patent Literature Search',
				prefix: 'npl-search',
				description: 'Search strategy for academic papers and standards',
				body: [
					'<role>You are a technical researcher skilled at finding non-patent literature relevant to patent examination.</role>',
					'',
					'<task>Develop a non-patent literature search strategy for the following invention.</task>',
					'',
					'<context>',
					'Invention: ${1:Brief description of the invention}',
					'Technical field: ${2:e.g., machine learning, organic chemistry}',
					'Priority date: ${3:YYYY-MM-DD}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify relevant academic databases (IEEE, ACM, PubMed, etc.)',
					'2. Suggest search queries for each database',
					'3. Identify relevant conference proceedings',
					'4. Suggest relevant technical standards (ISO, IEEE, 3GPP, etc.)',
					'5. Identify key researchers/groups in the field',
					'6. All literature must predate the priority date: ${3}',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Search Results Evaluation',
				prefix: 'search-eval',
				description: 'Evaluate and rank search results by relevance',
				body: [
					'<role>You are a patent examiner evaluating prior art search results.</role>',
					'',
					'<task>Evaluate the following search results and rank them by relevance to the target invention.</task>',
					'',
					'<context>',
					'Target invention features:',
					'${1:List the key features of the invention under examination}',
					'',
					'Search results to evaluate:',
					'${2:List of patent documents found}',
					'</context>',
					'',
					'<instructions>',
					'For each result:',
					'1. Identify which target features are disclosed',
					'2. Assess the relevance (A, X, Y, or background)',
					'3. Note the relevant passages/paragraphs',
					'4. Rank overall from most to least relevant',
					'Provide a summary table of feature coverage.',
					'</instructions>',
					'$0',
				],
			},
		],
	},
	{
		id: 'claim-analysis',
		label: 'Claim Analysis',
		description: 'Feature extraction, claim mapping, claim interpretation',
		icon: Codicon.listTree,
		templates: [
			{
				name: 'Claim Feature Extraction',
				prefix: 'claim-features',
				description:
					'Extract and structure technical features from patent claims',
				body: [
					'<role>You are a patent analyst expert in claim construction and feature extraction.</role>',
					'',
					'<task>Extract and structure the technical features from the following patent claims.</task>',
					'',
					'<context>',
					'Patent: ${1:Patent number}',
					'',
					'Claims:',
					'${2:Paste the claims here}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify each independent claim and its dependent claims',
					'2. For each independent claim, extract individual technical features',
					'3. Number each feature (F1, F2, F3...)',
					'4. For dependent claims, identify the additional features added',
					'5. Create a feature hierarchy showing which features are essential vs. optional',
					'6. Identify the \'characterizing portion\' (after \'characterized in that\')',
					'</instructions>',
					'',
					'<output_format>',
					'## Claim 1 (Independent)',
					'### Preamble',
					'- F1.1: ...',
					'### Characterizing Portion',
					'- F1.2: ...',
					'## Claim 2 (Dependent on 1)',
					'- F2.1: ...',
					'</output_format>',
					'$0',
				],
			},
			{
				name: 'Claim Interpretation',
				prefix: 'claim-interpret',
				description: 'Interpret claim terms and scope under EPC/USPTO rules',
				body: [
					'<role>You are a patent attorney specializing in claim interpretation under EPC and USPTO practice.</role>',
					'',
					'<task>Interpret the scope of the following claim, identifying ambiguities and proposing constructions.</task>',
					'',
					'<context>',
					'Jurisdiction: ${1|EPC,USPTO,PCT|}',
					'',
					'Claim text:',
					'${2:Paste the claim here}',
					'',
					'Relevant description passages:',
					'${3:Relevant passages from the description}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify key claim terms that require interpretation',
					'2. For each term, propose the broadest reasonable interpretation',
					'3. Flag any terms that are unclear or potentially indefinite',
					'4. Consider whether functional language (\'means for\', \'configured to\') is used',
					'5. Assess whether the claim is product, method, or use claim',
					'6. Note any potential support issues (Art. 84 EPC / 35 U.S.C. 112)',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Claim Mapping to Prior Art',
				prefix: 'claim-map',
				description: 'Map claim features to prior art disclosures',
				body: [
					'<role>You are a patent examiner mapping claim features against prior art documents.</role>',
					'',
					'<task>Create a detailed feature-by-feature mapping of the claim against the prior art document.</task>',
					'',
					'<context>',
					'Claim features:',
					'${1:List the extracted claim features (F1, F2, F3...)}',
					'',
					'Prior art document: ${2:Document number and title}',
					'Relevant passages:',
					'${3:Paste relevant prior art passages}',
					'</context>',
					'',
					'<instructions>',
					'For each claim feature:',
					'1. Find the corresponding disclosure in the prior art (quote specific passages)',
					'2. Assess: explicitly disclosed / implicitly disclosed / not disclosed',
					'3. Note any differences between the claim feature and the prior art disclosure',
					'4. Provide paragraph/column references for each mapping',
					'5. Summarize which features are met and which are distinguishing',
					'</instructions>',
					'',
					'<output_format>',
					'| Feature | Claim | Prior Art | Status | Reference |',
					'|---------|-------|-----------|--------|-----------|',
					'| F1 | ... | ... | Disclosed | [0023] |',
					'</output_format>',
					'$0',
				],
			},
			{
				name: 'Claim Dependency Chart',
				prefix: 'claim-deps',
				description: 'Create a claim dependency structure chart',
				body: [
					'<role>You are a patent analyst creating structured claim dependency charts.</role>',
					'',
					'<task>Analyze the claim set and create a dependency chart showing the claim tree structure.</task>',
					'',
					'<context>',
					'Claims:',
					'${1:Paste all claims here}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify all independent claims and their category (product/method/use)',
					'2. Map each dependent claim to its parent(s)',
					'3. Identify the additional feature(s) each dependent claim adds',
					'4. Flag any multiple dependency issues',
					'5. Identify the \'narrowest\' claim combinations',
					'6. Create a visual tree structure',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Two-Part Form Analysis',
				prefix: 'two-part',
				description: 'Analyze claims in two-part form (EPC Art. 84)',
				body: [
					'<role>You are an EPC patent examiner analyzing claims in two-part form per Rule 43(1) EPC.</role>',
					'',
					'<task>Analyze whether the following claim is correctly formulated in two-part form and suggest improvements.</task>',
					'',
					'<context>',
					'Claim:',
					'${1:Paste the claim}',
					'',
					'Closest prior art: ${2:Document number}',
					'Features disclosed in closest prior art:',
					'${3:List features known from prior art}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify the preamble (known features)',
					'2. Identify the characterizing portion (novel features)',
					'3. Assess whether the split is correct based on the closest prior art',
					'4. Suggest a corrected two-part formulation if needed',
					'5. Check conformity with Rule 43(1) EPC',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Unity of Invention Check',
				prefix: 'unity-check',
				description: 'Check unity of invention across claim set',
				body: [
					'<role>You are a patent examiner checking unity of invention under Art. 82 EPC / PCT Rule 13.</role>',
					'',
					'<task>Assess unity of invention for the following claim set.</task>',
					'',
					'<context>',
					'Independent claims:',
					'${1:List the independent claims}',
					'',
					'Known prior art:',
					'${2:Closest prior art documents and their disclosures}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify the common technical features across all independent claims',
					'2. Determine the \'special technical features\' (novel + inventive)',
					'3. Assess whether the common features make a contribution over the prior art',
					'4. If no unity: propose invention groups',
					'5. Apply the a posteriori unity analysis if prior art destroys unity',
					'</instructions>',
					'$0',
				],
			},
		],
	},
	{
		id: 'novelty-assessment',
		label: 'Novelty Assessment',
		description: 'Art. 54 EPC, feature comparison, novelty matrix',
		icon: Codicon.check,
		templates: [
			{
				name: 'Novelty Assessment (Art. 54 EPC)',
				prefix: 'novelty-54',
				description: 'Full novelty assessment under Article 54 EPC',
				body: [
					'<role>You are a European patent examiner conducting a novelty assessment under Article 54 EPC.</role>',
					'',
					'<task>Assess the novelty of the following claim against the cited prior art document.</task>',
					'',
					'<context>',
					'Claim under examination:',
					'${1:Paste the claim}',
					'',
					'Prior art document: ${2:Document number}',
					'Publication date: ${3:YYYY-MM-DD}',
					'Priority date of application: ${4:YYYY-MM-DD}',
					'',
					'Relevant disclosure:',
					'${5:Paste the relevant prior art passages}',
					'</context>',
					'',
					'<instructions>',
					'Apply the \'photographic\' novelty test:',
					'1. Extract each technical feature from the claim',
					'2. For each feature, determine if it is DIRECTLY AND UNAMBIGUOUSLY disclosed in the prior art',
					'3. Do NOT combine documents — novelty is assessed per single document',
					'4. Consider implicit disclosures only if they are inevitable consequences',
					'5. Conclude: novel (at least one feature not disclosed) or not novel (all features disclosed)',
					'',
					'Think step by step through each feature before reaching a conclusion.',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Novelty Matrix',
				prefix: 'novelty-matrix',
				description:
					'Create a novelty matrix comparing claims against multiple prior art docs',
				body: [
					'<role>You are a patent examiner creating a structured novelty comparison matrix.</role>',
					'',
					'<task>Create a novelty matrix comparing the claim features against multiple prior art documents.</task>',
					'',
					'<context>',
					'Claim features:',
					'${1:F1: feature 1\\nF2: feature 2\\nF3: feature 3}',
					'',
					'Prior art documents:',
					'D1: ${2:First prior art document}',
					'D2: ${3:Second prior art document}',
					'D3: ${4:Third prior art document}',
					'</context>',
					'',
					'<instructions>',
					'1. Create a matrix: features (rows) × documents (columns)',
					// allow-any-unicode-next-line
					'2. For each cell, mark: ✓ (disclosed), ~ (partially/implicitly), ✗ (not disclosed)',
					'3. Include specific paragraph references for each ✓ or ~',
					'4. Identify which document(s) anticipate the claim (all ✓)',
					'5. Identify distinguishing features per document',
					'6. Summarize the novelty conclusion',
					'</instructions>',
					'',
					'<output_format>',
					'| Feature | D1 | D2 | D3 |',
					'|---------|----|----|----| ',
					// allow-any-unicode-next-line
					'| F1 | ✓ [0012] | ✗ | ✓ [col.3] |',
					'',
					'## Conclusion',
					'</output_format>',
					'$0',
				],
			},
			{
				name: 'Selection Invention Novelty',
				prefix: 'novelty-selection',
				description: 'Assess novelty for selection inventions',
				body: [
					'<role>You are an EPO examiner assessing novelty of a selection invention following EPO Guidelines G-VI, 8.</role>',
					'',
					'<task>Assess whether the claimed selection is novel over the broader prior art disclosure.</task>',
					'',
					'<context>',
					'Claim (narrow selection):',
					'${1:Paste the claim with specific selection}',
					'',
					'Prior art (broad disclosure):',
					'${2:Paste the broad prior art range/genus}',
					'</context>',
					'',
					'<instructions>',
					'Apply the three criteria for novelty of selections:',
					'1. Is the selected sub-range narrow compared to the known range?',
					'2. Is the selected sub-range sufficiently far from the known examples/preferred embodiments?',
					'3. Is the selected sub-range not an arbitrary specimen but purposive?',
					'Consider both numerical ranges and chemical selections.',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Implicit Disclosure Analysis',
				prefix: 'novelty-implicit',
				description:
					'Analyze whether features are implicitly disclosed in prior art',
				body: [
					'<role>You are a patent examiner analyzing implicit disclosures in prior art documents.</role>',
					'',
					'<task>Determine whether the following claim feature is implicitly disclosed in the prior art.</task>',
					'',
					'<context>',
					'Claim feature in question:',
					'${1:The specific feature to analyze}',
					'',
					'Prior art document: ${2:Document number}',
					'Relevant passages:',
					'${3:Paste relevant prior art passages}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify what is explicitly stated in the prior art',
					'2. Determine if the claimed feature is an INEVITABLE consequence of the explicit disclosure',
					'3. Consider whether a skilled person would directly and unambiguously derive the feature',
					'4. Distinguish between \'could\' derive and \'would necessarily\' derive',
					'5. Cite relevant case law if applicable (e.g., T 0677/91)',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Prior Use / Public Availability',
				prefix: 'novelty-prior-use',
				description:
					'Assess novelty-destroying prior use or public availability',
				body: [
					'<role>You are a patent attorney analyzing prior public disclosure under Art. 54(2) EPC.</role>',
					'',
					'<task>Assess whether the following event constitutes a novelty-destroying public disclosure.</task>',
					'',
					'<context>',
					'Type of disclosure: ${1|Sale,Exhibition,Conference presentation,Publication,Product launch,Clinical trial|}',
					'Date of disclosure: ${2:YYYY-MM-DD}',
					'Priority date: ${3:YYYY-MM-DD}',
					'',
					'Details of the disclosure:',
					'${4:Describe what was disclosed, to whom, under what circumstances}',
					'',
					'Confidentiality obligations: ${5:Any NDAs or implied confidentiality?}',
					'</context>',
					'',
					'<instructions>',
					'1. Was the disclosure made available to the public (no confidentiality)?',
					'2. Was the disclosure before the priority date?',
					'3. Could a skilled person reproduce the invention from the disclosure?',
					'4. What technical features were actually made available?',
					'5. Consider Art. 55 EPC grace period if applicable',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Novelty Objection Draft',
				prefix: 'novelty-objection',
				description: 'Draft a novelty objection for an office action',
				body: [
					'<role>You are a patent examiner drafting a novelty objection under Art. 54 EPC.</role>',
					'',
					'<task>Draft a formal novelty objection based on the analysis below.</task>',
					'',
					'<context>',
					'Claim number: ${1:1}',
					'Prior art document: ${2:D1 - document number and title}',
					'',
					'Feature mapping:',
					'${3:Feature-by-feature mapping showing all features are disclosed}',
					'</context>',
					'',
					'<instructions>',
					'Draft the objection in formal examination style:',
					'1. State the legal basis (Art. 54(1)(2) EPC)',
					'2. Identify the prior art document and its publication date',
					'3. Map each claim feature to the specific disclosure (paragraph references)',
					'4. Use formal language: \'The subject-matter of claim X is not novel...\'',
					'5. Be precise about what is disclosed and where',
					'</instructions>',
					'$0',
				],
			},
		],
	},
	{
		id: 'inventive-step',
		label: 'Inventive Step',
		description: 'Problem-solution approach, could-would analysis',
		icon: Codicon.lightbulb,
		templates: [
			{
				name: 'Problem-Solution Approach',
				prefix: 'psa',
				description: 'Full problem-solution approach analysis (Art. 56 EPC)',
				body: [
					'<role>You are a European patent examiner applying the problem-solution approach to assess inventive step under Art. 56 EPC.</role>',
					'',
					'<task>Apply the three-step problem-solution approach to assess inventive step.</task>',
					'',
					'<context>',
					'Claim under examination:',
					'${1:Paste the claim}',
					'',
					'Closest prior art (D1): ${2:Document number}',
					'D1 disclosure:',
					'${3:Relevant D1 passages}',
					'',
					'Secondary document (D2, if applicable): ${4:Document number}',
					'D2 disclosure:',
					'${5:Relevant D2 passages}',
					'</context>',
					'',
					'<instructions>',
					'**Step 1: Determine the closest prior art**',
					'- Confirm D1 is the most promising starting point',
					'- Same purpose/effect, most relevant technical features in common',
					'',
					'**Step 2: Identify the distinguishing features and objective technical problem**',
					'- List features in the claim NOT disclosed by D1',
					'- Determine the technical effect of these distinguishing features',
					'- Formulate the objective technical problem (must not contain the solution)',
					'',
					'**Step 3: Could-would approach**',
					'- Would the skilled person, starting from D1 and faced with the objective technical problem, have arrived at the claimed solution?',
					'- Consider: Is there a teaching in D2 or common general knowledge that would prompt the modification?',
					'- Apply \'would\' not \'could\' — was there a motivation to combine?',
					'',
					'Think through each step carefully before concluding.',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Closest Prior Art Selection',
				prefix: 'closest-pa',
				description: 'Select and justify the closest prior art document',
				body: [
					'<role>You are a patent examiner selecting the closest prior art for an inventive step analysis.</role>',
					'',
					'<task>From the available prior art, select and justify the closest prior art document.</task>',
					'',
					'<context>',
					'Claim:',
					'${1:Paste the claim}',
					'',
					'Candidate prior art documents:',
					'${2:List the candidate documents with brief descriptions}',
					'</context>',
					'',
					'<instructions>',
					'For each candidate, evaluate:',
					'1. Same purpose or effect as the claimed invention?',
					'2. Number of technical features in common with the claim',
					'3. Requires fewest modifications to arrive at the claimed invention',
					'4. Is from the same or neighboring technical field?',
					'',
					'Select the document that forms the most promising starting point.',
					'Justify why alternatives are less suitable.',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Objective Technical Problem',
				prefix: 'otp',
				description: 'Formulate the objective technical problem',
				body: [
					'<role>You are a patent examiner formulating the objective technical problem per the problem-solution approach.</role>',
					'',
					'<task>Formulate the objective technical problem based on the distinguishing features.</task>',
					'',
					'<context>',
					'Closest prior art: ${1:Document number}',
					'',
					'Distinguishing features (not in closest prior art):',
					'${2:List the distinguishing features}',
					'',
					'Technical effect of distinguishing features:',
					'${3:What technical effect do these features achieve?}',
					'</context>',
					'',
					'<instructions>',
					'1. Verify the technical effect is actually achieved (supported by the application)',
					'2. Formulate the problem as \'How to [achieve the technical effect]?\'',
					'3. Ensure the problem does NOT contain or point to the solution',
					'4. Check: is this a partial problem (bonus effect)? If so, re-formulate',
					'5. Consider whether the problem needs to be reformulated based on the prior art',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Could-Would Analysis',
				prefix: 'could-would',
				description: 'Detailed could-would obviousness analysis',
				body: [
					'<role>You are a patent examiner performing the could-would analysis for inventive step.</role>',
					'',
					'<task>Determine whether the skilled person WOULD (not merely could) have arrived at the claimed invention.</task>',
					'',
					'<context>',
					'Starting point (closest prior art): ${1:D1 document}',
					'Objective technical problem: ${2:The formulated OTP}',
					'Claimed solution: ${3:The distinguishing features}',
					'',
					'Available teachings:',
					'${4:D2 and other documents / common general knowledge}',
					'</context>',
					'',
					'<instructions>',
					'Analyze:',
					'1. Does D2 (or CGK) address the same or similar technical problem?',
					'2. Does D2 suggest the specific modification needed?',
					'3. Would the skilled person have a motivation to combine D1 and D2?',
					'4. Are there any obstacles or prejudices against the combination?',
					'5. Is the combination \'obvious to try\' or merely \'possible\'?',
					'6. Consider secondary indicators (unexpected effects, long-felt need, commercial success)',
					'',
					'Apply \'would\' standard: Was there a reasonable expectation of success and motivation?',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Inventive Step Objection Draft',
				prefix: 'is-objection',
				description: 'Draft an inventive step objection for an office action',
				body: [
					'<role>You are a patent examiner drafting an inventive step objection under Art. 56 EPC.</role>',
					'',
					'<task>Draft a formal inventive step objection using the problem-solution approach.</task>',
					'',
					'<context>',
					'Claim: ${1:Claim number}',
					'Closest prior art: ${2:D1}',
					'Secondary reference: ${3:D2}',
					'Distinguishing features: ${4:Features not in D1}',
					'Objective technical problem: ${5:The OTP}',
					'Teaching in D2: ${6:What D2 teaches relevant to the OTP}',
					'</context>',
					'',
					'<instructions>',
					'Draft the objection following the standard structure:',
					'1. \'The closest prior art is D1, which discloses...\' (list common features)',
					'2. \'The subject-matter of claim X differs from D1 in that...\' (distinguishing features)',
					'3. \'The technical effect of this difference is...\' → \'The objective technical problem is...\'',
					'4. \'D2 teaches...\' (relevant teaching)',
					'5. \'The skilled person would therefore...\' (motivation to combine)',
					'6. \'The subject-matter of claim X does not involve an inventive step (Art. 56 EPC)\'',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Secondary Indicators of Inventive Step',
				prefix: 'secondary-indicators',
				description: 'Evaluate secondary indicators supporting inventive step',
				body: [
					'<role>You are a patent attorney evaluating secondary indicators (auxiliary considerations) for inventive step.</role>',
					'',
					'<task>Evaluate the strength of secondary indicators supporting inventive step.</task>',
					'',
					'<context>',
					'Claimed invention: ${1:Brief description}',
					'',
					'Alleged secondary indicators:',
					'${2:List claimed secondary indicators (unexpected effects, long-felt need, commercial success, etc.)}',
					'',
					'Evidence provided:',
					'${3:Available evidence for the indicators}',
					'</context>',
					'',
					'<instructions>',
					'For each indicator, assess:',
					'1. Is the evidence substantiated (not merely alleged)?',
					'2. Is there a causal link to the distinguishing features?',
					'3. How strong is this indicator per EPO case law?',
					'',
					'Common indicators to consider:',
					'- Unexpected technical effect',
					'- Long-felt need solved',
					'- Commercial success',
					'- Overcoming a technical prejudice',
					'- Bonus effect (one-way street situation)',
					'</instructions>',
					'$0',
				],
			},
		],
	},
	{
		id: 'patent-drafting',
		label: 'Patent Drafting',
		description: 'Claims writing, description, abstract',
		icon: Codicon.edit,
		templates: [
			{
				name: 'Independent Claim Drafting',
				prefix: 'draft-claim',
				description: 'Draft an independent patent claim',
				body: [
					'<role>You are a patent attorney drafting claims for a European patent application.</role>',
					'',
					'<task>Draft an independent claim based on the invention description below.</task>',
					'',
					'<context>',
					'Invention description:',
					'${1:Describe the invention}',
					'',
					'Closest prior art: ${2:What is known in the art}',
					'Novel features: ${3:What is new about this invention}',
					'Claim category: ${4|Product (apparatus/device),Method (process),Use,System|}',
					'</context>',
					'',
					'<instructions>',
					'1. Use two-part form (EPC style) with \'characterized in that\'',
					'2. Preamble: features known from the closest prior art',
					'3. Characterizing portion: novel and inventive features',
					'4. Use clear, precise technical language',
					'5. Avoid unnecessary limitations — claim broadly but with support',
					'6. Each feature should be a separate clause',
					'7. Use reference signs in parentheses where helpful',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Dependent Claim Set',
				prefix: 'draft-deps',
				description: 'Draft a set of dependent claims',
				body: [
					'<role>You are a patent attorney creating a dependent claim set for fallback protection.</role>',
					'',
					'<task>Draft dependent claims that provide progressive narrowing from the independent claim.</task>',
					'',
					'<context>',
					'Independent claim:',
					'${1:Paste the independent claim}',
					'',
					'Additional features available in the description:',
					'${2:List additional features that can be claimed}',
					'',
					'Key embodiments to protect:',
					'${3:Describe the most important specific embodiments}',
					'</context>',
					'',
					'<instructions>',
					'1. Create 5-10 dependent claims in order of decreasing scope',
					'2. Each dependent claim adds exactly one feature or feature group',
					'3. Ensure a path from broadest to narrowest preferred embodiment',
					'4. Consider both single and multiple dependency',
					'5. Include claims covering key commercial embodiments',
					'6. Use consistent terminology with the independent claim',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Abstract Drafting',
				prefix: 'draft-abstract',
				description: 'Draft a patent abstract',
				body: [
					'<role>You are a patent attorney drafting an abstract for a patent application.</role>',
					'',
					'<task>Draft a concise abstract (max 150 words) for the following invention.</task>',
					'',
					'<context>',
					'Title: ${1:Title of the invention}',
					'Independent claim:',
					'${2:Paste the main independent claim}',
					'',
					'Technical problem solved:',
					'${3:What problem does the invention solve?}',
					'</context>',
					'',
					'<instructions>',
					'1. Start with the title/field of the invention',
					'2. State the technical problem',
					'3. Summarize the solution (key features from the independent claim)',
					'4. Mention the principal use',
					'5. Maximum 150 words',
					'6. Include reference signs in parentheses matching the main figure',
					'7. Do not include commercial statements or subjective claims of merit',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Description Section Drafting',
				prefix: 'draft-desc',
				description: 'Draft a section of the patent description',
				body: [
					'<role>You are a patent attorney drafting the description of a European patent application.</role>',
					'',
					'<task>Draft the ${1|Technical Field,Background Art,Summary of Invention,Brief Description of Drawings,Detailed Description|} section.</task>',
					'',
					'<context>',
					'Invention: ${2:Brief description of the invention}',
					'Independent claim: ${3:Paste the independent claim}',
					'',
					'Technical details to include:',
					'${4:Specific technical details for this section}',
					'</context>',
					'',
					'<instructions>',
					'- Use clear, technical language avoiding marketing terms',
					'- Include reference signs matching the drawings',
					'- Provide basis for all claim features',
					'- Use \'embodiment\' language for specific implementations',
					'- Distinguish essential features from optional ones',
					'- Follow Rule 42 EPC requirements for description content',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Claim Amendment',
				prefix: 'draft-amend',
				description: 'Draft a claim amendment with basis in the description',
				body: [
					'<role>You are a patent attorney amending claims in response to an office action.</role>',
					'',
					'<task>Draft an amended claim that overcomes the objection while maintaining broad protection.</task>',
					'',
					'<context>',
					'Current claim:',
					'${1:Paste current claim}',
					'',
					'Objection to overcome:',
					'${2:Describe the examiner\'s objection}',
					'',
					'Available basis in description:',
					'${3:Paste relevant description paragraphs}',
					'',
					'Prior art cited: ${4:Prior art document(s)}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify the minimum amendment needed to overcome the objection',
					'2. Ensure the amendment has clear basis in the description (Art. 123(2) EPC)',
					'3. Do not extend protection beyond the original application (Art. 123(3) EPC)',
					'4. Use exact language from the description where possible',
					'5. Provide specific paragraph references for each added feature',
					'6. Consider whether dependent claims can be incorporated',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Method Claim from Apparatus',
				prefix: 'draft-method',
				description:
					'Draft a corresponding method claim from an apparatus claim',
				body: [
					'<role>You are a patent attorney drafting corresponding method claims from apparatus claims.</role>',
					'',
					'<task>Draft a method claim corresponding to the following apparatus/device claim.</task>',
					'',
					'<context>',
					'Apparatus claim:',
					'${1:Paste the apparatus/device claim}',
					'</context>',
					'',
					'<instructions>',
					'1. Convert structural features to method steps',
					'2. Use active voice and \'-ing\' form for steps',
					'3. Maintain the same scope — do not add or remove features',
					'4. Order steps logically (temporal sequence)',
					'5. Keep two-part form if applicable',
					'6. Ensure the method claim is independently infringeable',
					'</instructions>',
					'$0',
				],
			},
		],
	},
	{
		id: 'freedom-to-operate',
		label: 'Freedom to Operate',
		description: 'Claim scope, infringement, design-around',
		icon: Codicon.shield,
		templates: [
			{
				name: 'FTO Analysis',
				prefix: 'fto',
				description: 'Freedom to operate analysis for a product/process',
				body: [
					'<role>You are a patent attorney conducting a freedom to operate (FTO) analysis.</role>',
					'',
					'<task>Assess whether the proposed product/process risks infringing the identified patents.</task>',
					'',
					'<context>',
					'Proposed product/process:',
					'${1:Describe the product or process to analyze}',
					'',
					'Target market: ${2:Countries/regions}',
					'',
					'Patents to analyze:',
					'${3:List patent numbers and their status (granted/pending)}',
					'</context>',
					'',
					'<instructions>',
					'For each patent:',
					'1. Identify the granted independent claims',
					'2. Map each claim element to the proposed product/process',
					'3. Assess: literal infringement? Doctrine of equivalents?',
					'4. Check patent status and territorial coverage',
					'5. Identify risk level: High / Medium / Low / No risk',
					'6. Suggest design-around options for high-risk patents',
					'7. Note any claims that are potentially invalid',
					'</instructions>',
					'',
					'<output_format>',
					'## FTO Summary',
					'| Patent | Status | Risk | Key Claim | Analysis |',
					'|--------|--------|------|-----------|----------|',
					'## Detailed Analysis',
					'## Design-Around Options',
					'## Recommendations',
					'</output_format>',
					'$0',
				],
			},
			{
				name: 'Infringement Claim Chart',
				prefix: 'infringement-chart',
				description:
					'Create a claim chart mapping product features to claim elements',
				body: [
					'<role>You are a patent litigation attorney preparing an infringement claim chart.</role>',
					'',
					'<task>Create a detailed claim chart mapping the accused product to the patent claim.</task>',
					'',
					'<context>',
					'Patent claim:',
					'${1:Paste the claim}',
					'',
					'Accused product/process:',
					'${2:Describe the accused product or process in detail}',
					'</context>',
					'',
					'<instructions>',
					'For each claim element:',
					'1. Quote the exact claim language',
					'2. Describe how the accused product meets this element',
					'3. Provide evidence references (product documentation, specs, etc.)',
					'4. If an element is not met literally, analyze doctrine of equivalents',
					'5. Flag any elements that are clearly not met',
					'</instructions>',
					'',
					'<output_format>',
					'| # | Claim Element | Accused Product | Met? | Evidence |',
					'|---|--------------|-----------------|------|----------|',
					'</output_format>',
					'$0',
				],
			},
			{
				name: 'Design-Around Strategy',
				prefix: 'design-around',
				description: 'Develop strategies to design around a patent',
				body: [
					'<role>You are a patent engineer developing design-around strategies.</role>',
					'',
					'<task>Propose design-around options to avoid infringing the following patent claim.</task>',
					'',
					'<context>',
					'Patent claim to avoid:',
					'${1:Paste the claim}',
					'',
					'Current product/process design:',
					'${2:Describe the current design that potentially infringes}',
					'',
					'Technical constraints:',
					'${3:Any constraints that must be maintained}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify the essential claim elements (must ALL be present for infringement)',
					'2. For each essential element, propose alternatives that fall outside the claim scope',
					'3. Assess technical feasibility of each alternative',
					'4. Consider doctrine of equivalents — is the alternative different enough?',
					'5. Rank options by: feasibility, cost, risk of still infringing',
					'6. Recommend the best design-around strategy',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Patent Landscape Analysis',
				prefix: 'landscape',
				description: 'Analyze the patent landscape in a technical area',
				body: [
					'<role>You are a patent strategist analyzing the competitive patent landscape.</role>',
					'',
					'<task>Analyze the patent landscape for the following technology area.</task>',
					'',
					'<context>',
					'Technology area: ${1:e.g., solid-state batteries}',
					'Key players to analyze: ${2:List of companies}',
					'Time period: ${3:e.g., 2018-2024}',
					'Geographic scope: ${4:e.g., EP, US, CN, JP, KR}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify the major patent holders and their portfolio sizes',
					'2. Map technology sub-areas and which players dominate each',
					'3. Identify white spaces (under-patented areas)',
					'4. Analyze filing trends over time',
					'5. Identify potential blocking patents',
					'6. Highlight recent patent activity that may indicate strategic shifts',
					'7. Provide recommendations for patent strategy',
					'</instructions>',
					'$0',
				],
			},
		],
	},
	{
		id: 'office-action',
		label: 'Office Action Response',
		description: 'Arguments, amendments, interview prep',
		icon: Codicon.reply,
		templates: [
			{
				name: 'Office Action Response',
				prefix: 'oa-response',
				description: 'Draft a complete response to an office action',
				body: [
					'<role>You are a European patent attorney drafting a response to an office action from the EPO.</role>',
					'',
					'<task>Draft a response addressing all objections raised in the office action.</task>',
					'',
					'<context>',
					'Application number: ${1:EP application number}',
					'Office action date: ${2:YYYY-MM-DD}',
					'',
					'Objections raised:',
					'${3:Summarize the examiner\'s objections}',
					'',
					'Prior art cited:',
					'${4:List the cited documents}',
					'',
					'Current claims:',
					'${5:Paste current claims}',
					'',
					'Available description passages for amendment:',
					'${6:Paste relevant description paragraphs}',
					'</context>',
					'',
					'<instructions>',
					'Structure the response as:',
					'1. **Introduction** - Reference the office action and deadline',
					'2. **Amendments** - Describe each claim amendment with basis citations',
					'3. **Arguments** - Address each objection systematically:',
					'   - For novelty: Show distinguishing features not in the prior art',
					'   - For inventive step: Apply PSA showing why combination is not obvious',
					'   - For clarity/support: Explain how amendments address the issues',
					'4. **Conclusion** - Request grant or further examination',
					'',
					'Be persuasive but precise. Cite specific paragraphs and claim features.',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Art. 123(2) Basis Check',
				prefix: 'basis-check',
				description: 'Check added matter for proposed claim amendments',
				body: [
					'<role>You are a patent attorney checking compliance with Art. 123(2) EPC (no added matter).</role>',
					'',
					'<task>Verify that the proposed amendment has a clear basis in the application as filed.</task>',
					'',
					'<context>',
					'Proposed amended claim:',
					'${1:Paste the proposed amendment}',
					'',
					'Original claim:',
					'${2:Paste the original claim}',
					'',
					'Application as filed (relevant passages):',
					'${3:Paste relevant original description paragraphs}',
					'</context>',
					'',
					'<instructions>',
					'1. Identify each feature added or modified compared to the original claim',
					'2. For each change, find the EXACT basis in the application as filed',
					'3. Apply the \'gold standard\': Would the skilled person derive the amendment directly and unambiguously from the original disclosure?',
					'4. Check for intermediate generalizations (isolating features from a specific embodiment)',
					'5. Flag any features that may constitute added matter',
					'6. Provide specific paragraph references for each basis citation',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Inventive Step Argument',
				prefix: 'is-argument',
				description: 'Draft arguments defending inventive step',
				body: [
					'<role>You are a patent attorney arguing inventive step in response to an Art. 56 EPC objection.</role>',
					'',
					'<task>Draft persuasive arguments defending the inventive step of the claimed invention.</task>',
					'',
					'<context>',
					'Examiner\'s reasoning:',
					'${1:Summarize the examiner\'s inventive step objection}',
					'',
					'Closest prior art used: ${2:D1}',
					'Secondary reference: ${3:D2}',
					'',
					'Distinguishing features (per examiner):',
					'${4:Features the examiner acknowledges are not in D1}',
					'',
					'Your counter-arguments:',
					'${5:Key points you want to make}',
					'</context>',
					'',
					'<instructions>',
					'Structure arguments using PSA framework:',
					'1. **Challenge closest prior art selection** (if appropriate) - argue a different starting point',
					'2. **Challenge the objective technical problem** - argue the effect is different/greater',
					'3. **Challenge the would-combine reasoning**:',
					'   - D2 addresses a different problem',
					'   - Combining D1+D2 requires hindsight',
					'   - There is no motivation to modify D1 as suggested',
					'   - Technical obstacles/prejudice against the combination',
					'4. **Invoke secondary indicators** if available',
					'',
					'Use T-decision case law to support arguments where relevant.',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Oral Proceedings Preparation',
				prefix: 'oral-prep',
				description: 'Prepare for oral proceedings before the EPO',
				body: [
					'<role>You are a patent attorney preparing for oral proceedings before an EPO Examining or Opposition Division.</role>',
					'',
					'<task>Prepare a structured brief for oral proceedings.</task>',
					'',
					'<context>',
					'Case: ${1:Application/Opposition number}',
					'Stage: ${2|Examination,Opposition,Appeal|}',
					'',
					'Issues to be discussed:',
					'${3:List the main issues}',
					'',
					'Our position:',
					'${4:Summarize current position}',
					'',
					'Opponent\'s/Examiner\'s position:',
					'${5:Summarize the opposing position}',
					'</context>',
					'',
					'<instructions>',
					'Prepare:',
					'1. **Opening statement** (2-3 minutes)',
					'2. **Arguments per issue** with supporting evidence',
					'3. **Anticipated counterarguments** and rebuttals',
					'4. **Auxiliary requests** (fallback claim sets with arguments)',
					'5. **Key case law** to cite',
					'6. **Questions to expect** from the division',
					'7. **Red lines** — what we cannot concede',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Clarity and Support Fixes',
				prefix: 'clarity-fix',
				description: 'Fix Art. 84 EPC clarity and support objections',
				body: [
					'<role>You are a patent attorney addressing clarity and support objections under Art. 84 EPC.</role>',
					'',
					'<task>Propose amendments to fix the following clarity/support issues.</task>',
					'',
					'<context>',
					'Current claim with issues:',
					'${1:Paste the claim}',
					'',
					'Examiner\'s objections:',
					'${2:List the specific Art. 84 objections}',
					'',
					'Description support available:',
					'${3:Paste relevant description passages}',
					'</context>',
					'',
					'<instructions>',
					'For each objection:',
					'1. Identify the specific clarity/support issue',
					'2. Propose claim language that resolves it',
					'3. Show basis in the description for any new language',
					'4. Ensure the fix does not inadvertently narrow scope unnecessarily',
					'5. Check for consistency with other claims in the set',
					'',
					'Common issues to address:',
					'- Relative terms without reference point',
					'- Functional features without clear meaning',
					'- Inconsistent terminology',
					'- Missing essential features',
					'- Unclear scope of \'comprising\' vs \'consisting of\'',
					'</instructions>',
					'$0',
				],
			},
			{
				name: 'Opposition Arguments',
				prefix: 'opposition',
				description: 'Draft arguments for patent opposition proceedings',
				body: [
					'<role>You are a patent attorney preparing arguments for opposition proceedings under Art. 99-105 EPC.</role>',
					'',
					'<task>Draft opposition arguments against the granted patent.</task>',
					'',
					'<context>',
					'Patent under opposition: ${1:Patent number}',
					'Granted claims:',
					'${2:Paste the granted claims}',
					'',
					'Grounds for opposition: ${3|Lack of novelty (Art. 100(a) + 54),Lack of inventive step (Art. 100(a) + 56),Insufficient disclosure (Art. 100(b)),Extension beyond original filing (Art. 100(c))|}',
					'',
					'Evidence:',
					'${4:List the prior art documents and evidence}',
					'</context>',
					'',
					'<instructions>',
					'Structure the opposition:',
					'1. **Admissibility** — filed within 9 months, proper grounds',
					'2. **Claim construction** — how the claims should be interpreted',
					'3. **Main arguments** per ground of opposition',
					'4. **Attack on each independent claim** — feature-by-feature analysis',
					'5. **Attack on dependent claims** — why they do not save the patent',
					'6. **Request** — revocation or limitation to specific claims',
					'</instructions>',
					'$0',
				],
			},
		],
	},
];
